#region References

using Server.Mobiles;
using System;
using System.Collections.Generic;
using Server.ACC.CSS.Systems.Ancient;
using Server.Engines.ArenaSystem;
using Server.Engines.Doom;
using Server.Engines.HunterKiller;
using Server.Engines.Quests;
using Server.Engines.Quests.Ambitious;
using Server.Engines.Quests.RitualQuest;
using Server.Engines.RisingTide;
using Server.Items;
using Server.Mobiles.Swiateczne;

#endregion

namespace Server
{
	public static class SpeedInfo
	{
		private const double DefaultSpeed = 1.0;

		private const double MinDelay = 0.1;
		private const double MaxDelay = 0.5;
		private const double MinDelayWild = 0.15;
		private const double MaxDelayWild = 0.8;

		public static bool GetSpeeds(BaseCreature bc, ref double activeSpeed, ref double passiveSpeed)
		{
			if (!_SpeedTable.TryGetValue(bc.GetType(), out activeSpeed))
			{
				var parentType = bc.GetType().BaseType;
				if (parentType == null || !_SpeedTable.TryGetValue(parentType, out activeSpeed))
				{
					activeSpeed = DefaultSpeed;
					Console.WriteLine($"No speed defined for {bc.GetType().Name} or its parent {parentType.Name}");
				}
			}

			passiveSpeed = activeSpeed * 2f;

			if (bc.IsMonster)
			{
				activeSpeed = Math.Clamp(activeSpeed * 1.3f, MinDelayWild, MaxDelayWild);
				passiveSpeed = Math.Clamp(passiveSpeed * 1.3f, MinDelayWild, MaxDelayWild);
			}

			if (bc is BaseNelderimGuard)
			{
				// Guards have to be faster when in fight
				activeSpeed = Math.Min(0.15, activeSpeed);
			}

			return true;
		}

		public static double TransformMoveDelay(BaseCreature bc, double delay)
		{
			var max = bc.IsMonster ? MaxDelayWild : MaxDelay;

			if (!bc.IsDeadPet && (bc.ReduceSpeedWithDamage || bc.IsSubdued))
			{
				var offset = bc.Stam / (double)bc.StamMax;

				if (offset < 1.0) delay += (max - delay) * (1.0 - offset);

				var hitsScalar = bc.Hits < bc.HitsMax * 0.25f ? 1.2 : 1.0;
				delay *= hitsScalar;
			}

			if (bc.IsMonster)
				delay = Math.Clamp(delay, MinDelayWild, MaxDelayWild);
			else
				delay = Math.Clamp(delay, MinDelay, MaxDelay);

			return delay;
		}

		private static Dictionary<Type, double> _SpeedTable = new();

		static SpeedInfo()
		{
			foreach (var speedInfoEntry in _SpeedDefinitions)
			{
				foreach (var type in speedInfoEntry.types)
					//We crash on purpose if we have duplicates
					_SpeedTable.Add(type, speedInfoEntry.activeSpeed);
			}
		}

		private record SpeedInfoEntry(double activeSpeed, Type[] types);

		private static SpeedInfoEntry[] _SpeedDefinitions =
		[
			/* Veeeeery Slooooow */
			new(0.55,
			[
				typeof(Aminia),
				typeof(BexilPunchingBag),
				typeof(MonsterNestEntity),
				typeof(Mummy2),
				typeof(Mummy3),
				typeof(Tangle),
				typeof(UnfrozenMummy),
				typeof(XmlQuestNPC)
			]),
			/* Very Slow */
			new(0.3,
			[
				typeof(BarakSlime),
				typeof(Boar),
				typeof(BogThing),
				typeof(FrostOoze),
				typeof(FrostTroll),
				typeof(GazerLarva),
				typeof(Ghoul),
				typeof(HeadlessOne),
				typeof(Juggernaut),
				typeof(Jwilson),
				typeof(MoundOfMaggots),
				typeof(PlagueBeast),
				typeof(Quagmire),
				typeof(RestlessSoul),
				typeof(RottingCorpse),
				typeof(ShadowWisp),
				typeof(Skeleton),
				typeof(Slime),
				typeof(Walrus),
				typeof(Zombie)
			]),
			/* Slow */
			new(0.25,
			[
				typeof(AntLion),
				typeof(ArcticOgreLord),
				typeof(BlackSolenWorker),
				typeof(BloodElemental),
				typeof(Bogle),
				typeof(BoneKnight),
				typeof(BoneMagi),
				typeof(Brigand),
				typeof(BullFrog),
				typeof(Cat),
				typeof(Chicken),
				typeof(Cow),
				typeof(CrystalElemental),
				typeof(Cyclops),
				typeof(DalharukElghinn),
				typeof(DarknightCreeper),
				typeof(EarthElemental),
				typeof(ElderGazer),
				typeof(EnslavedGargoyle),
				typeof(Ettin),
				typeof(Feniks),
				typeof(FleshGolem),
				typeof(Gazer),
				typeof(GiantSpider),
				typeof(Gibberling),
				typeof(Golem),
				typeof(GolemController),
				typeof(GreaterDragon),
				typeof(IceElemental),
				typeof(JukaLord),
				typeof(JukaMage),
				typeof(LesserHordeDaemon),
				typeof(LichLord),
				typeof(Lizardman),
				typeof(Mongbat),
				typeof(Mummy),
				typeof(NBurugh),
				typeof(NDeloth),
				typeof(NDzahhar),
				typeof(NGorogon),
				typeof(NKatrill),
				typeof(NSilshashaszals),
				typeof(NSkeletalDragon),
				typeof(NStarozytnyLodowySmok),
				typeof(NStarozytnySmok),
				typeof(NSzeol),
				typeof(Ogre),
				typeof(OgreLord),
				typeof(Orc),
				typeof(OrcBomber),
				typeof(OrcishMage),
				typeof(PatchworkSkeleton),
				typeof(Pig),
				typeof(Rat),
				typeof(Ratman),
				typeof(RatmanMage),
				typeof(RedSolenWorker),
				typeof(Serado),
				typeof(Sewerrat),
				typeof(Sheep),
				typeof(SkitteringHopper),
				typeof(StrongMongbat),
				typeof(SummonedDaemon),
				typeof(SummonedEarthElemental),
				typeof(SummonedFireElemental),
				typeof(SummonedWaterElemental),
				typeof(SwampTentacle),
				typeof(TerathanDrone),
				typeof(Titan),
				typeof(Treefellow),
				typeof(Troll),
				typeof(WhippingVine),
				typeof(WladcaDemonow),
				typeof(xCommonArcaneDaemon),
				typeof(Zhoaminth)
			]),
			/* Medium */
			new(0.2,
			[
				typeof(Abscess),
				typeof(Actor),
				typeof(AgapiteColossus),
				typeof(AgapiteElemental),
				typeof(AlbinoSquirrel),
				typeof(Alligator),
				typeof(AmethystDragon),
				typeof(AmethystDrake),
				typeof(AncientLich),
				typeof(AncientSeaMonster),
				typeof(Arachne),
				typeof(ArcaneFey),
				typeof(ArcaneFiend),
				typeof(ArcherNelderimGuard),
				typeof(ArenaManager),
				typeof(Artist),
				typeof(BagiennaLama),
				typeof(BagusGagakArcher),
				typeof(BagusGagakCreeper),
				typeof(BagusGagakFencer),
				typeof(BagusGagakLord),
				typeof(BagusGagakLumberjack),
				typeof(BagusGagakShaman),
				typeof(BagusGagakWarrior),
				typeof(BakeKitsune),
				typeof(BaseAmbitiousSolenQueen),
				typeof(BaseEscort),
				typeof(BaseGuildmaster),
				typeof(BaseHealer),
				typeof(BaseQuester),
				typeof(BaseVendor),
				typeof(Betrayer),
				typeof(BetrayerBoss),
				typeof(Bird),
				typeof(BlackBear),
				typeof(BlackLizard),
				typeof(BlackMarketMerchant),
				typeof(BlackSolenInfiltratorWarrior),
				typeof(BlackSolenWarrior),
				typeof(BladeSpirits),
				typeof(Bogling),
				typeof(Boner),
				typeof(BronzeColossus),
				typeof(BronzeElemental),
				typeof(BrownBear),
				typeof(BulbousPutrification),
				typeof(Bull),
				typeof(Centaur),
				typeof(ChiefParoxysmus),
				typeof(ChiefParoxysmusAvatar),
				typeof(Chiikkaha),
				typeof(ClockworkExodus),
				typeof(CommonDaemon),
				typeof(CommonHordeDaemon),
				typeof(CommonMoloch),
				typeof(CopperColossus),
				typeof(CopperElemental),
				typeof(CorporealBrume),
				typeof(Corpser),
				typeof(CorrosiveSlime),
				typeof(Crane),
				typeof(CrystalDaemon),
				typeof(CrystalHydra),
				typeof(CrystalLatticeSeeker),
				typeof(CrystalSeaSerpent),
				typeof(CrystalVortex),
				typeof(CrystalWisp),
				typeof(Cursed),
				typeof(CuSidhe),
				typeof(Daemon),
				typeof(DarkWisp),
				typeof(DarkWolfFamiliar),
				typeof(DeathAdder),
				typeof(DeathSpiderFamiliar),
				typeof(DeathVortex),
				typeof(DeathwatchBeetle),
				typeof(DeathwatchBeetleHatchling),
				typeof(DeepSeaSerpent),
				typeof(DemonicznySluga),
				typeof(DesertOstard),
				typeof(Devourer),
				typeof(DiamondDragon),
				typeof(DiamondDrake),
				typeof(Dog),
				typeof(Dolphin),
				typeof(Doppleganger),
				typeof(Dragon),
				typeof(DragonsFlameGrandMage),
				typeof(DragonsFlameMage),
				typeof(Drake),
				typeof(DreadHorn),
				typeof(DullCopperColossus),
				typeof(DullCopperElemental),
				typeof(ElfBrigand),
				typeof(EliteNelderimGuard),
				typeof(EmeraldDragon),
				typeof(EmeraldDrake),
				typeof(EnslavedSatyr),
				typeof(EscortableMage),
				typeof(EscortablePeasant),
				typeof(EttinLord),
				typeof(EvilHealer),
				typeof(EvilMage),
				typeof(EvilMageLord),
				typeof(EvilWanderingHealer),
				typeof(Executioner),
				typeof(ExodusOverseer),
				typeof(Fence),
				typeof(Ferret),
				typeof(FetidEssence),
				typeof(FiendOfEarth),
				typeof(FieryGoblinSapper),
				typeof(FireBeetle),
				typeof(FireGargoyle),
				typeof(Flurry),
				typeof(FrostSpider),
				typeof(Gaman),
				typeof(Gargoyle),
				typeof(GargoyleEnforcer),
				typeof(GaryTheDungeonMaster),
				typeof(GiantIceWorm),
				typeof(GiantRat),
				typeof(GiantSerpent),
				typeof(GiantToad),
				typeof(Gnaw),
				typeof(Goat),
				typeof(Goblin),
				typeof(GoblinSapper),
				typeof(GoblinWarrior),
				typeof(GoldenColossus),
				typeof(GoldenElemental),
				typeof(GoreFiend),
				typeof(Gorilla),
				typeof(GorskiWilk),
				typeof(GrayGoblin),
				typeof(GreaterAntLion),
				typeof(GreaterArcaneDaemon),
				typeof(GreaterChaosDaemon),
				typeof(GreaterDaemon),
				typeof(GreaterHordeDaemon),
				typeof(GreaterMoloch),
				typeof(GreaterMongbat),
				typeof(GreaterRedSolenWarrior),
				typeof(GreaterRedSolenWorker),
				typeof(Gregorio),
				typeof(Grim),
				typeof(GrimmochDrummel),
				typeof(Grobu),
				typeof(Guardian),
				typeof(Gypsy),
				typeof(HarborMaster),
				typeof(Harpy),
				typeof(Harrower),
				typeof(HarrowerTentacles),
				typeof(HeavyNelderimGuard),
				typeof(HellHorse),
				typeof(HellHound),
				typeof(Hind),
				typeof(HordeMinionFamiliar),
				typeof(HungaNekahiXBowmen),
				typeof(Hydra),
				typeof(IceFiend),
				typeof(IceLizard),
				typeof(IceSerpent),
				typeof(Imp),
				typeof(Impaler),
				typeof(InsaneDryad),
				typeof(InterredGrizzle),
				typeof(JackRabbit),
				typeof(JukaWarrior),
				typeof(KamiennaWyverna),
				typeof(Kappa),
				typeof(KazeKemono),
				typeof(KhaldunSummoner),
				typeof(KhaldunZealot),
				typeof(KorahaTilkiLord),
				typeof(KorahaTilkiPeasant),
				typeof(KorahaTilkiShaman),
				typeof(KorahaTilkiSpearman),
				typeof(KorahaTilkiWarrior),
				typeof(KorahaTilkiXBowmen),
				typeof(Kraken),
				typeof(KusznikMorrlok),
				typeof(LadyLissith),
				typeof(LadyMelisande),
				typeof(LadySabrix),
				typeof(LavaLizard),
				typeof(LavaSerpent),
				typeof(LesserArcaneDaemon),
				typeof(LesserChaosDaemon),
				typeof(LesserDaemon),
				typeof(LesserGoblinSapper),
				typeof(LesserMoloch),
				typeof(Llama),
				typeof(LodowySmok),
				typeof(LordMorrlok),
				typeof(LucznikMorrlok),
				typeof(Lurg),
				typeof(LysanderGathenwale),
				typeof(MageNelderimGuard),
				typeof(MagMorrlok),
				typeof(MantraEffervescence),
				typeof(MasterJonath),
				typeof(MasterTheophilus),
				typeof(MeerCaptain),
				typeof(MeerEternal),
				typeof(MeerMage),
				typeof(MeerWarrior),
				typeof(Minotaur),
				typeof(MinotaurBoss),
				typeof(MinotaurCaptain),
				typeof(MinotaurLord),
				typeof(MinotaurMage),
				typeof(MinotaurScout),
				typeof(Minter),
				typeof(Mistral),
				typeof(MLDryad),
				typeof(MlodaKobra),
				typeof(MlodyGorskiSmok),
				typeof(MlodyLodowySmok),
				typeof(MlodyOgnistySmok),
				typeof(MondainQuester),
				typeof(MonstrousInterredGrizzle),
				typeof(MordercaMorrlok),
				typeof(MorgBergen),
				typeof(MorrlokWarHorse),
				typeof(Motyl),
				typeof(MougGuur),
				typeof(MountainGoat),
				typeof(MrocznaCzelusc),
				typeof(NatureFury),
				typeof(NBaseTalkingNPC),
				typeof(NChimera),
				typeof(NecroMageLord),
				typeof(NelderimAncientLich),
				typeof(NelderimDragon),
				typeof(NHalleht),
				typeof(Ninja),
				typeof(NPCElghin),
				typeof(NPirateCaptain),
				typeof(NPirateCrew),
				typeof(NPrzeklety),
				typeof(NSarag),
				typeof(NZapomniany),
				typeof(OgnistaWyverna),
				typeof(OgnistyNiewolnik),
				typeof(OgnistySmok),
				typeof(OgnistySzaman),
				typeof(OgnistyWojownik),
				typeof(OgromnyWilk),
				typeof(OrcBrute),
				typeof(OrcCaptain),
				typeof(OrcishLord),
				typeof(OrcScout),
				typeof(PackLlama),
				typeof(PanSmierc),
				typeof(ParoxysmusSwampDragon),
				typeof(PestilentBandage),
				typeof(PetParrot),
				typeof(PirateCrew),
				typeof(PomiotPajaka),
				typeof(PrastaryLodowySmok),
				typeof(PrastaryOgnistySmok),
				typeof(PRidgeback),
				typeof(Protector),
				typeof(PSavage),
				typeof(PSavage1),
				typeof(PSavageShaman),
				typeof(Putrefier),
				typeof(Qingniao),
				typeof(Rabbit),
				typeof(RagingGrizzlyBear),
				typeof(Reaper),
				typeof(RedBeetle),
				typeof(RedDeath),
				typeof(RedSolenInfiltratorWarrior),
				typeof(RedSolenWarrior),
				typeof(Rend),
				typeof(Reptalon),
				typeof(RidableLlama),
				typeof(Ridgeback),
				typeof(RubyDragon),
				typeof(RubyDrake),
				typeof(RustMonster),
				typeof(Saliva),
				typeof(Samurai),
				typeof(SapphireDragon),
				typeof(SapphireDrake),
				typeof(SaragAwatar),
				typeof(Satyr),
				typeof(Savage),
				typeof(SavageRidgeback),
				typeof(ScaledSwampDragon),
				typeof(Scorpion),
				typeof(Sculptor),
				typeof(SeaHorse),
				typeof(SeaSerpent),
				typeof(SerpentsFangAssassin),
				typeof(SerpentsFangHighExecutioner),
				typeof(ServantOfSemidar),
				typeof(Sfinks),
				typeof(ShadowFiend),
				typeof(ShadowIronColossus),
				typeof(ShadowIronElemental),
				typeof(ShadowWispFamiliar),
				typeof(ShadowWyrm),
				typeof(ShimmeringEffusion),
				typeof(ShimmeringFerret),
				typeof(Silk),
				typeof(SkalnyJaszczur),
				typeof(SkalnyKocur),
				typeof(SkalnyLew),
				typeof(SkalnyOgar),
				typeof(SkeletalDragon),
				typeof(SkeletalKnight),
				typeof(SkeletalMount),
				typeof(SkoczekLesny),
				typeof(SkorpionKrolewski),
				typeof(Snake),
				typeof(SnieznaLama),
				typeof(SnowBakeKitsune),
				typeof(SpawnedOrcishLord),
				typeof(SpeckledScorpion),
				typeof(Spellbinder),
				typeof(Sphynx),
				typeof(Squirrel),
				typeof(StandardNelderimGuard),
				typeof(StarozytnaMumia),
				typeof(StaryLodowySmok),
				typeof(StaryOgnistySmok),
				typeof(StoneGargoyle),
				typeof(StoneHarpy),
				typeof(SwampDragon),
				typeof(Swoop),
				typeof(SzafirowyJednorozec),
				typeof(Szavetra),
				typeof(TalkingBaseEscortable),
				typeof(TalkingDrake),
				typeof(TalkingSeekerOfAdventure),
				typeof(TavaraSewel),
				typeof(Tempest),
				typeof(TerathanMatriarch),
				typeof(TerathanWarrior),
				typeof(TigersClawMaster),
				typeof(TigersClawThief),
				typeof(TilkiBug),
				typeof(TilkiSmallBug),
				typeof(TormentedMinotaur),
				typeof(TownEscortable),
				typeof(Travesty),
				typeof(TravestyDog),
				typeof(Troglodyte),
				typeof(TrollLord),
				typeof(TropicalBird),
				typeof(UpadlyJednorozec),
				typeof(UpadlyKirin),
				typeof(ValoriteColossus),
				typeof(ValoriteElemental),
				typeof(VampireBat),
				typeof(VampireBatFamiliar),
				typeof(VeriteColossus),
				typeof(VeriteElemental),
				typeof(Virulent),
				typeof(VitVarg),
				typeof(VitVargArcher),
				typeof(VitVargLord),
				typeof(VitVargMage),
				typeof(VitVargWarrior),
				typeof(VitVargWorker),
				typeof(WailingBanshee),
				typeof(WandererOfTheVoid),
				typeof(WanderingHealer),
				typeof(WarHorse),
				typeof(WarLlama),
				typeof(WaterElemental),
				typeof(Widmak),
				typeof(WladcaJezioraLawy),
				typeof(WladcaPiaskow),
				typeof(WojownikMorrlok),
				typeof(WolfArcher),
				typeof(WolfHunter),
				typeof(WolfPredator),
				typeof(WolfPup),
				typeof(WolfShaman),
				typeof(WolfWarrior),
				typeof(Wraith),
				typeof(Wyvern),
				typeof(xCommonChaosDaemon),
				typeof(xMoloch),
				typeof(YomotsuElder),
				typeof(YomotsuPriest),
				typeof(YomotsuWarrior),
				typeof(ZimowyOgre),
				typeof(ZimowyOgreLord),
				typeof(ZmiennyDar)
			]),
			/* Fast */
			new(0.175,
			[
				typeof(AbysmalHorror),
				typeof(AirElemental),
				typeof(Anchimayen),
				typeof(AncientWyrm),
				typeof(BagusGagakNinja),
				typeof(Balron),
				typeof(BaronowaFrozen),
				typeof(BlackSolenInfiltratorQueen),
				typeof(BlackSolenQueen),
				typeof(BoneDemon),
				typeof(Cougar),
				typeof(DemonKnight),
				typeof(DireWolf),
				typeof(DreadSpider),
				typeof(Eagle),
				typeof(EnergyVortex),
				typeof(ExodusBoss),
				typeof(ExodusMinion),
				typeof(ExodusMinionArmored),
				typeof(FireElemental),
				typeof(FireSteed),
				typeof(ForestOstard),
				typeof(FrenziedOstard),
				typeof(GargoyleDestroyer),
				typeof(GiantBlackWidow),
				typeof(GreatHart),
				typeof(GreyWolf),
				typeof(GrizzlyBear),
				typeof(HellCat),
				typeof(HellSteed),
				typeof(HireBard),
				typeof(HireBardArcher),
				typeof(HireBeggar),
				typeof(HireFighter),
				typeof(HireMage),
				typeof(HirePaladin),
				typeof(HirePeasant),
				typeof(HireRanger),
				typeof(HireRangerArcher),
				typeof(HireSailor),
				typeof(HireThief),
				typeof(HKMobile),
				typeof(Horse),
				typeof(IceSnake),
				typeof(JaskiniowyJaszczur),
				typeof(JaskiniowyZukJuczny),
				typeof(Kirin),
				typeof(KorahaTilkiDancer),
				typeof(LadyOfTheSnow),
				typeof(LavaSnake),
				typeof(LesserHiryu),
				typeof(Lich),
				typeof(LordOaks),
				typeof(MadPumpkinSpirit),
				typeof(Oni),
				typeof(OphidianKnight),
				typeof(OphidianMage),
				typeof(OphidianWarrior),
				typeof(PackHorse),
				typeof(PlagueSpawn),
				typeof(PolarBear),
				typeof(RatmanArcher),
				typeof(Ravager),
				typeof(RedSolenInfiltratorQueen),
				typeof(RedSolenQueen),
				typeof(RevenantLion),
				typeof(Ronin),
				typeof(RuneBeetle),
				typeof(SavageRider),
				typeof(SavageShaman),
				typeof(SerpentineDragon),
				typeof(ShadowKnight),
				typeof(Silvani),
				typeof(SilverSteed),
				typeof(SnieznyKirin),
				typeof(SnieznyRumak),
				typeof(SnowElemental),
				typeof(SnowLeopard),
				typeof(SpectralArmour),
				typeof(StormElemental),
				typeof(Succubus),
				typeof(SummonedAirElemental),
				typeof(TerathanAvenger),
				typeof(TimberWolf),
				typeof(ToxicElemental),
				typeof(TsukiWolf),
				typeof(Unicorn),
				typeof(WhiteWolf),
				typeof(WhiteWyrm),
				typeof(Worg),
				typeof(Yamandon)
			]),
			/* Very Fast */
			new(0.15,
			[
				typeof(AntyMageMob),
				typeof(AntyTamerMob),
				typeof(AntyWarriorMob),
				typeof(BagiennyKoszmar),
				typeof(BagusGagakLightCav),
				typeof(Barracoon),
				typeof(Beetle),
				typeof(ChaosDragoon),
				typeof(ChaosDragoonElite),
				typeof(Efreet),
				typeof(EliteNinja),
				typeof(EtherealWarrior),
				typeof(EvilSpellbook),
				typeof(FanDancer),
				typeof(FleshRenderer),
				typeof(Hiryu),
				typeof(KorahaTilkiPikador),
				typeof(Leviathan),
				typeof(Mephitis),
				typeof(MotherWolf),
				typeof(Neira),
				typeof(Nightmare),
				typeof(OphidianArchmage),
				typeof(OphidianMatriarch),
				typeof(Panther),
				typeof(PoisonElemental),
				typeof(PredatorHellCat),
				typeof(PSavageRider),
				typeof(RaiJu),
				typeof(Rikktor),
				typeof(SandVortex),
				typeof(Semidar),
				typeof(SilverSerpent),
				typeof(SkoczekZPodmroku),
				typeof(VitVargAmazon),
				typeof(VitVargBerserker),
				typeof(VitVargCook),
				typeof(VitVargCutler),
				typeof(Wisp)
			]),
			/* Ultra Fast */
			new(0.1,
			[
				typeof(Changeling),
				typeof(Coil),
				typeof(CorruptedSoul),
				typeof(Guile),
				typeof(Ilhenir),
				typeof(Irk),
				typeof(JezdziecMorrlok),
				typeof(KhaldunRevenant),
				typeof(LadyJennifyr),
				typeof(LadyMarai),
				typeof(Malefic),
				typeof(MasterMikael),
				typeof(Meraktus),
				typeof(Miasma),
				typeof(MountedNelderimGuard),
				typeof(NDuchNatury),
				typeof(NPoleAntymagiczne),
				typeof(NUpiorWalki),
				typeof(Phoenix),
				typeof(Pixie),
				typeof(Pyre),
				typeof(Revenant),
				typeof(SirPatrick),
				typeof(SpecialNelderimGuard),
				typeof(Spite),
				typeof(Thrasher),
				typeof(Twaulo),
				typeof(VorpalBunny)
			]),
		];
	}
}
