//Created by Milva
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;

namespace Server.Gumps
{
    public class Gingerbreadquestgump : Gump
    {
        public static void Initialize()
        {
            CommandSystem.Register("Gingerbreadquestgump", AccessLevel.GameMaster, new CommandEventHandler(Gingerbreadquestgump_OnCommand));
		} 
		
		private static void Gingerbreadquestgump_OnCommand( CommandEventArgs e ) 
		{ 
			e.Mobile.SendGump( new Gingerbreadquestgump( e.Mobile ) ); 
		}

        public Gingerbreadquestgump(Mobile owner)
            : base(50, 50) 
		{
            this.Closable=true;
			this.Disposable=true;
			this.Dragable=true;
			this.Resizable=false;

			AddImageTiled(14, 10, 377, 433, 2524);
			AddImageTiled(9, 6, 388, 13, 1143);
			AddImageTiled(9, 433, 384, 11, 1143);
			AddImage(389, 191, 3003, 1152);
			AddImage(13, 19, 5057, 173);
			AddImage(389, 17, 3003, 1152);
			AddTextEntry(112, 40, 166, 20, 33, 0, @"   Piernikowe zadanie!");
			AddButton(163, 385, 247, 248, 0, GumpButtonType.Reply, 0);
			AddImage(108, 29, 96);
			AddImage(104, 420, 96);
			AddItem(313, 30, 11225);
			AddItem(43, 38, 11228);
            AddHtml(59, 85, 302, 284, "<BODY>" +	
"<BASEFONT COLOR=Red>Z pieczeniem świątecznych deserów jest tyle do zrobienia!<BR><BR>" +
"<BASEFONT COLOR=Red>Tutaj byłem bardzo zajęty mieszaniem i czytaniem przepisów<BR><BR>" +
"<BASEFONT COLOR=Red>Nigdy nie zauważyłem, że wszedł Złodziej Piernikowy!<BR>" +
"<BASEFONT COLOR=Red>I uciekłem z całym moim piernikowym ciastem!!<BR>" +
"<BASEFONT COLOR=Red>To ciasto jest naprawdę potrzebne, abym mógł...<BR><BR>" +
"<BASEFONT COLOR=Red>Dokończtć dziś piernikowe ciasteczka.<BR><BR>" +
"<BASEFONT COLOR=Red>Proszę, jeśli możesz znaleźć tego złodzieja piernika...<BR><BR>" +
"<BASEFONT COLOR=Red>I przynieś mi moje ciasto, wynagrodzę Ci moim specjalnym prezentem!.<BR><BR>" +
"<BASEFONT COLOR=Red>Mój kolekcjonerski.... jedyny w swoim rodzaju prezent!.<BR><BR>" +
"<BASEFONT COLOR=Red>Będzie tu gdzieś biegał w okolicy Śnieżnej Przystani! !<BR><BR>" +
                             "</BODY>", false, true);

			
            AddImage(13, 119, 5057, 173);
            AddImage(25, 37, 2701, 152);
			AddImage(106, 70, 96 );
			AddItem(0, 114, 11233);
			AddItem(-2, 368, 11233);
			AddItem(1, 236, 11233);
            AddButton(163, 385, 247, 248, 0, GumpButtonType.Reply, 0);

        }
       

        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch(info.ButtonID)
            {
                case 0:
				{
					break;
				}

            }
        }
    }
}