//Created by Milva
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;

namespace Server.Gumps
{
    public class  SantaQuestGump : Gump
    {
        public static void Initialize()
        {
            CommandSystem.Register(" SantaQuestGump", AccessLevel.GameMaster, new CommandEventHandler(SantaQuestGump_OnCommand));
		} 
		
		private static void  SantaQuestGump_OnCommand( CommandEventArgs e ) 
		{ 
			e.Mobile.SendGump( new  SantaQuestGump( e.Mobile ) ); 
		}

        public SantaQuestGump(Mobile owner)
            : base(50, 50) 
		{
            this.Closable=true;
			this.Disposable=true;
			this.Dragable=true;
			this.Resizable=false;
            AddPage(0);
            AddImageTiled(14, 10, 377, 433, 2524);
            AddImageTiled(14, 425, 379, 18, 3501);
            AddImage(14, 18, 2712, 37);
            AddImage(14, 220, 2712, 37);
            AddTextEntry(120, 44, 167, 25, 33, 0, @"Zadanie od Pana!");
            AddHtml(35, 83, 346, 281, "<BODY>" +	
"<BASEFONT COLOR=Red>Ho HO Ho Wesolego Swieta Pana!<BR><BR>" +
"<BASEFONT COLOR=Red>No... byly wesole... az do wczoraj<BR><BR>" +
"<BASEFONT COLOR=Red>Mój elf właśnie zgłosił czającego się złego elfa!<BR>" +
"<BASEFONT COLOR=Red>Postanowili więc sprawdzić sklep z zabawkami!!<BR>" +
"<BASEFONT COLOR=Red>ten zły elf ukradł...<BR><BR>" +
"<BASEFONT COLOR=Red>Naszą ostatnią beczkę czerwonej farby!!!.<BR><BR>" +
"<BASEFONT COLOR=Red>Naprawdę potrzebujemy tej beczki z farbą do wykończenia zabawek!...<BR><BR>" +
"<BASEFONT COLOR=Red>Proszę, jeśli możesz znaleźć tego elfa i sprowadzić go z powrotem do mnie!.<BR><BR>" +
"<BASEFONT COLOR=Red>Otrzymasz mój specjalny prezent.<BR><BR>" +
"<BASEFONT COLOR=Red>Może warto udać się w okolicę Sal Białego Wilka!<BR><BR>" +
"<BASEFONT COLOR=Red>Które byłoby idealnym miejscem dla złego elfa!<BR><BR>" +
                             "</BODY>", false, true);
            AddImageTiled(14, 7, 379, 18, 3501);
            AddItem(44, 17, 14943);
            AddItem(311, 17, 14951);
            AddItem(61, 361, 14983);
            AddItem(79, 357, 14984);
		
            AddButton(163, 385, 247, 248, 0, GumpButtonType.Reply, 0);

        }
       

        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch(info.ButtonID)
            {
                case 0:
				{
					break;
				}

            }
        }
    }
}