name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore UONelderim/ServUO.sln
      - name: Build
        run: dotnet build UONelderim/ServUO.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test UONelderim/ServUO.sln --configuration Release --no-build
